Feature/20 database model for the session
akvo/partos-pat pull request #21
Opened 2024-09-12 13:46 UTC by ifirmawan

## TODO/DONE

- [ ] Models & Migration
- [ ] ENUM Sector
- [ ] Database Seeder
- [ ] Unit tests

2024-09-13 12:54 UTC, dedenbangkit requested changes

2024-09-13 12:54 UTC, dedenbangkit commented on backend/api/v1/v1_sessions/constants.py
Hi @ifirmawan please replace with this (you might need to remake-the-migration)

Policy coherence
International fair agreements
Equality, inclusion & diversity
Human rights
Global Citizen & Global Engagement
Collaborate on sustainable development
Promoting peace and stabilising conflict
Nature, environment & climate justice
Fair distribution & access to basic amenities
Humanitarian emergency aid

2024-09-13 12:54 UTC, dedenbangkit commented on backend/api/v1/v1_users/management/commands/fake_users_seeder.py
> +            sex_code = {
gender_code

2024-09-13 12:54 UTC, dedenbangkit commented on backend/api/v1/v1_users/management/commands/fake_users_seeder.py
> +            sex = sex_code[gender]
remove

2024-09-13 12:54 UTC, dedenbangkit commented on backend/api/v1/v1_users/management/commands/fake_users_seeder.py
> +                gender=gender,
gender_code[gender]

2024-09-13 12:56 UTC, ifirmawan commented on backend/api/v1/v1_sessions/constants.py
Ok mas, on it

2024-09-16 04:21 UTC, dedenbangkit approved these changes

2024-09-16 04:22 UTC, merged